public class RunWrapper{
    public  static <T> T run(Callable<T> callable) throws XException {
        try {
            return callable.call();
        } catch (SQLException sqlEx){
            throw new XException("DB exception,exception: "+sqlEx.getCause());
        }catch (XException x){
            throw x;
        }catch (Exception e) {
            throw new XException(e);
        }
    }


    public  static <T> T runWithArgsCheck(Callable<T> callable,Object args) throws XException {
        try {
            ValidationResult result = ValidateHelper.validateEntity(args);
            if(result.isHasErrors()) throw new Exception(result.getErrorMsg().toString());
            return callable.call();
        } catch (SQLException sqlEx){
            throw new XException("DB exception,exception: "+sqlEx.getCause());
        }catch (XException x){
            throw x;
        }catch (Exception e) {
            throw new XException(e);
        }
    }
}
